---
title: "**¿Quién justifica qué? El rol del sentido de injusticia en las justificaciones de violencia en contexto de protesta**"
author: |
   | Martín Venegas^[martin.venegas@ug.uchile.cl]
   | \vspace{.5cm} Departamento de Sociología, Universidad de Chile.
   | Juan Diego García Castro
   | \vspace{.5cm} Universidad de Costa Rica, Sede de Occidente y 
   | Centro de Estudios de Conflicto y Cohesión Social (COES), Chile.
   | Juan Carlos Castillo
   | Departamento de Sociología, Universidad de Chile y 
   | Centro de Estudios de Conflicto y Cohesión Social (COES), Chile.
   
date: "04-08-2023"
output:
  pdf_document:
    number_sections: true
    toc: no
bibliography: input/bib/tesis.bib
csl: input/bib/apa.csl
header-includes:
    - \usepackage{graphicx}
    - \usepackage{float}
    - \usepackage{times}           # Times New Roman
    - \usepackage{caption}
    - \usepackage{graphicx}
    - \usepackage{float}
    - \usepackage{booktabs}
    - \usepackage{longtable}
    - \usepackage{array}
    - \usepackage{multirow}
    - \usepackage{wrapfig}
    - \usepackage{float}
    - \usepackage{colortbl}
    - \usepackage{pdflscape}
    - \usepackage{tabu}
    - \usepackage{threeparttable}    
geometry: margin=2cm
linestretch: '1.0'
urlcolor: blue
link-citations: yes
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

<!-- # Summary -->

# Introducción

<!-- (highlighting theoretical and empirical debates on your topic and deficits in the literature that your project would address) -->


La violencia es fenómeno que tiene implicancias en todas las esferas de la vida: causa sufrimiento, humillación y, muchas veces, va aparejada de grandes cambios sociales. Durante el año 2019, Chile atravesó una gran movilización social comúnmente denominada _estallido social_, la cual se caracterizó por un grandes niveles de represión, así como de violencia en la protesta. Este panorama fue de la mano con una disminución en la justificación del actuar de las policías, y una mayor justificación del actuar de protestantes [@ELSOC2019]. A raíz de este contexto, emerge la pregunta sobre qué razones o qué características determinan que los individuos justifiquen ambos tipos de violencia.

El estudio de las justificaciones de la violencia distingue si esta se ejerce por el cambio social o por el control social [@Blumenthal1972; @Gerber2017a]. En la literatura empírica se ha encontrado que las justificaciones de ambos tipos de violencia se pueden explicar a partir de la pertenencia a grupos desaventajados [@Gamson1970; @Arthur1994; @Thompson2004], la ideología [@Gerber2017b; @Perkins2006; @Lemieux2012] y las percepciones de justicia procesal [@Jackson2013; @Gerber2017; @Bradford2017]. Esta última explicación es la que más ha recibido atención en el último tiempo, sin embargo, en el presente estudio se ha partido de la premisa que la justicia no es un concepto unidimensional, sino uno multidimensional [@Tornblom2007]. A raíz de ello, se ha propuesto integrar a la justicia distributiva como una dimensión relevante para explicar las dinámicas de la justificación de la violencia. La pregunta que ha guiado el estudio es: ¿Cuál es la relación entre el sentido de injusticia distributiva y las justificaciones de la violencia en contexto de protesta, tanto por el cambio social, como por el control social, en Chile al año 2019?

# Hipótesis y método

A partir de una muestra de 711 casos de los datos del Estudio Longitudinal Social de Chile (ELSOC) se pusieron a prueba cuatro hipótesis. Por un lado, que quienes evaluarán la distribución de ingresos como más injusta tenderían a justificar más la violencia por el cambio social (H1a) y menos por el control social (H1b). Por otro lado, que individuos que pertenecen a grupos desaventajados justificarían más la violencia por el cambio social (H2a) y menos por el control social (H2b), en la medida que aumentaran sus evaluaciones de injusticia. Para probar las hipótesis, y en consideración de la naturaleza de las variables, se utilizaron modelos de regresión logística ordinal para tres situaciones de violencia: que estudiantes tiren piedras a carabineros, que carabineros repriman marchas pacificas y que carabineros desalojen tomas a la fuerza (escalas Likert de 1 a 5, siendo _1: Nunca se justifica_ hasta _5: Siempre se justifica_). Para cada una de estas situaciones, se indagó en el efecto que tenía el sentido de injusticia distributiva, operacionalizado según la teoría de las evalauciones de injusticia [@Jasso1980]. En concreto, se utilizaron tres tipos de sentido de injusticia distributiva: las evaluaciones que hacen los entrevistados sobre sus ingresos, las evaluaciones para los ingresos de un obrero hipotético y las evaluaciones para los ingresos de un gerente hipotético. Se controlaron los efectos por los predictores más relevantes según literatura (pertenencia a grupos desaventajados, ideología y percepción de justicia procesal).

# Resumen de resultados y discusión.

Los resultados mostraron evidencia a favor para el primer par de hipótesis (H1a y H2a) y evidencia contraria para el segundo par de hipótesis (H2a y H2b). Para el primer par de hipótesis, se encontró un efecto diferenciado para cada situación de violencia. Por un lado, quienes evalúan más injusticia en los ingresos de los gerentes justifican más la violencia por el cambio social. Esto sugiere que al buscar razones para justificar las tácticas de protesta violenta, las personas suelen encontrarlas en la situación de los estratos más altos de la sociedad, en tanto fuente de descontento que podría ser transformarse en un motivante. Por otro lado, se encontró que quienes evalúan menos injusticia en los ingresos de los obreros justifican más la violencia por el control social. Esto sugiere una lógica racional, en la medida que una evaluación de menor injusticia en la situación de los más desfavorecidos puede ser leído como una satisfacción con el _status quo_ y un llamado a su mantención, labor principal de las policías. Sin embargo, la evidencia sugiere que esta lógica deja de operar cuando la violencia de las policías es desproporcionada, siendo la ideología el principal motivante en estos casos, lo cual es consistente con literatura previa [@Gerber2017b]. Para el segundo par de hipótesis, se encontró que las evaluaciones de injusticia tenían un efecto atenuante en que individuos de grupos desaventajados justificarán más la violencia por el cambio social y menos la violencia por el control social. Se propone un potencial efecto en la elección de las variables y sus formas de medición. Nuevos estudios podrían profundizar la relación entre el sentido de injusticia distributiva y las justificaciones de violencia a partir de 1) aproximaciones longitudinales, 2) mediciones más precisas de los conceptos o 3) nuevas metodologías (e.g. encuestas factoriales).


# Referencias

::: {#refs}
:::
